# Generated by Django 3.2.12 on 2022-02-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_alter_promotion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='key_prom',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
