# Generated by Django 3.2.12 on 2022-02-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_promotion_prom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='username',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
